### ISSUE TITLE
Missing data and headshots for Jimmy Gomez, CA-34

### ISSUE THREAD

**Issue by chrisalcantara** [CivilServiceUSA/us-house#1]
Xavier Becerra resigned from the post and Jimmy Gomez is now the representative of this district.

**Comment by manifestinteractive** [comment]
Resolved by PR #5. I will update the API's data in the next hour.

**Comment by manifestinteractive** [comment]
@chrisalcantara just a heads up that all new data and headshots are integrated into both our API and this repository now :)  Thanks for getting these posted so I knew there were changes ;)
