### ISSUE TITLE
ethnicity errors

### ISSUE THREAD

**Issue by jaytimm** [CivilServiceUSA/us-house#10]
Hi guys,

I absolutely love your work.  

I have noted some errors in ethnicity classifications for the new 1116th House data.

Xochitl Torres Small (NM-02) is Hispanic. Deb Haaland (NM-01) & Sharice Davids (KS-03) are Native American. All three are presently listed as White.

**Comment by nickoneill** [comment]
Thanks @jaytimm! I think these were intended to be "unspecified" until we could nail down all that specific data, can you link to a source for these so I can go through and check some other new folks too?

**Comment by manifestinteractive** [comment]
Ooooh, you’re my hero.  We were actually under a time crunch to track down sources.  I will get these updated this evening :)

First day with some great new elected officials, I appreciate your efforts to make sure we get this data 100% correct :)

**Comment by nickoneill** [comment]
Made these updates in the source doc, will close when the updated data is pushed live. Thank you @jaytimm, lmk if you see any others!

**Comment by jaytimm** [comment]
Wonderful! You guys do beast-work!  Let me know if you ever need a hand.
