### ISSUE TITLE
Louise Slaughter still listed in us-house.csv

### ISSUE THREAD

**Issue by hodgesmr** [CivilServiceUSA/us-house#11]
Louise Slaughter [is still listed in the CSV](https://github.com/CivilServiceUSA/us-house/blob/v1.2.0/us-house/data/us-house.csv#L297). She passed away on March 16, 2018 and NY-25 is now held by [Joseph Morelle](https://en.wikipedia.org/wiki/Joseph_Morelle).

**Comment by nickoneill** [comment]
Thanks @hodgesmr! I don't know how I missed this as Morelle was part of the 2018 general election. I'll update the doc with his info and we'll close this when it's been pushed out to the api and websites.
