### ISSUE TITLE
Previous Congresses

### ISSUE THREAD

**Issue by jaytimm** [CivilServiceUSA/us-house#22]
Hi guys,

I was curious if there was a way to access data files for previous houses, namely, the 115th?

Thanks!!

**Comment by manifestinteractive** [comment]
Civil Services only maintains the current set of data, however, we do have the previous data archived in a spreadsheet.

https://docs.google.com/spreadsheets/d/1GkjhUhsN0NQ_IKI90vu3w0UCR7C7rv7KYhOnKVwQJ8k/edit?usp=sharing

**Comment by jaytimm** [comment]
Thank you kindly.
