### ISSUE TITLE
Some Rep updates needed in 116th

### ISSUE THREAD

**Issue by jaytimm** [CivilServiceUSA/us-house#23]
Hi guys,

I have noticed some representatives that need updating for the 116th House.

(AZ-8) Trent Franks -> Debbie Lesko
(OH-12) Pat Tiberi -> Troy Balderson
(TX-27) Blake Farenthold -> Michael Cloud
(UT-3) Jason Chaffetz -> John Curtis

As always, thanks for these lovely resources.

**Comment by nickoneill** [comment]
Thanks for the note @jaytimm! I think these are all resignations that must have not been on my list of updates for 2018. I will work on getting the new data in the doc here ASAP.
